server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    preferIpAddress: true
redis:
  host: localhost
  port: 6379